config/routes.rb
Writz::Application.routes.draw do

  devise_for :users
  root to: "welcome#index"

  get "welcome/index"
  get "welcome/about"
  
  resources :stories do
    resources :story_components
  end

  

end

app/models/contributer.rb
class Contributer < ActiveRecord::Base

  belongs_to :user
  belongs_to :story_component

  # allow_nil for tests
  delegate :name, :email, to: :user, allow_nil: true

end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :story_components
  has_many :contributers
  has_many :users, through: :contributers

  validates :title, presence: true

  COMPONENT_TYPES = ['intro', 'conflict', 'resolution']

  def missing_component_types
    self.story_components.collect(&:component_type) - COMPONENT_TYPES
  end

  def complete?
    self.missing_component_types.empty?
  end

  def intro
    self.story_components.where(component_type: 'intro').first
  end

  def conflict
    self.story_components.where(component_type: 'conflict').first
  end

  def resolution
    self.story_components.where(component_type: 'resolution').first
  end

end

app/models/story_component.rb
class StoryComponent < ActiveRecord::Base
  belongs_to :story
  belongs_to :contributer

  COMPONENT_TYPES = ['intro', 'conflict', 'resolution']
  validates_inclusion_of :component_type, in: COMPONENT_TYPES
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :sc_ownerships, foreign_key: :contributer_id, class_name: "StoryComponent"

  validates :password, exclusion: {in: ["Password"],
    message: "must be changed." }
  validates :name, presence: true
  validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :update_sanitized_params, if: :devise_controller?

  protected

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(
      :email,
      :password,
      :password_confirmation,
      :name
    )}
    devise_parameter_sanitizer.for(:sign_in) {|u| u.permit(
      :email,
      :password,
      :password_confirmation,
      :name
    )}
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all.paginate(page: params[:page], per_page: 7)
  end

  def show
    @story = Story.find(params[:id])
    
    if @story.intro
      @intro_id = @story.intro.id
      @intro_body = @story.intro.body
    else
      @intro_id = ''
      @intro_body = 'This story needs an introduction!'
    end

    if @story.conflict
      @conflict_id = @story.conflict.id
      @conflict_body = @story.conflict.body
    else
      @conflict_id = ''
      @conflict_body = 'This story needs a conflict!'
    end

    if @story.resolution
      @resolution_id = @story.resolution.id
      @resolution_body = @story.resolution.body
    else
      @resolution_id = ''
      @resolution_body = 'This story needs a resolution!'
    end

    render(:layout => false) if request.xhr?
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params.merge(creator_id: current_user.id))

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'You started a story!' }
        format.json { render action: 'show', status: :created, location: @story }
      else
        format.html { render action: 'new' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
  end

  private

  def story_params
    params.require(:story).permit(:title)
  end

end

app/controllers/story_components_controller.rb
class StoryComponentsController < ApplicationController
  before_action :set_story_component, only: [:show, :edit, :update, :destroy]

  # GET /story_components/new
  def new
    @story_component = StoryComponent.new
    @story = Story.find(params[:story_id])
    @component_types = ['intro', 'conflict', 'resolution']
    render(:layout => false) if request.xhr?
  end

  def edit
    @story = Story.find(params[:story_id])
    @story_component = StoryComponent.find(params[:id])
    @component_types = ['intro', 'conflict', 'resolution']
    render(:layout => false) if request.xhr?
  end

  # POST /story_components
  # POST /story_components.json
  def create
    #@story_component = StoryComponent.new(story_component_params)
    @story_component = current_user.sc_ownerships.build(story_component_params.merge( 
      contributer_id: current_user.id, 
      story_id: params[:story_id] ))
    @story = Story.find(params[:story_id])

    respond_to do |format|
      if @story_component.save
        format.html { redirect_to @story, notice: 'Story component was successfully created.' }
        format.json { render action: 'show', status: :created, location: @story_component }
      else
        format.html { render action: 'new' }
        format.json { render json: @story_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /story_components/1
  # PATCH/PUT /story_components/1.json
  def update
    @story = Story.find(params[:story_id])
    respond_to do |format|
      if @story_component.update(story_component_params)
        format.html { redirect_to @story, notice: 'Story component was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @story_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /story_components/1
  # DELETE /story_components/1.json
  def destroy
    @story_component.destroy
    respond_to do |format|
      format.html { redirect_to story_components_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story_component
      @story_component = StoryComponent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_component_params
      params.require(:story_component).permit(:contributer_id, :component_type, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @top_stories = Story.all.sample(3)
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(content)
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, 
      autolink: true, 
      space_after_headers: true, 
      fenced_code_blocks: true)
    @markdown.render(content)
  end

end

app/helpers/story_components_helper.rb
module StoryComponentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Writz
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body class='all'
    = render file: 'layouts/header'

    div class='container wrap'
      - if flash[:notice]
          div class='alert alert-success'
            button type='button' class='close' data-dismiss='alert' aria-hidden='true' &times;
            = flash[:notice]
      - elsif flash[:error]
          div class='alert alert-danger'
            button type='button' class='close' data-dismiss='alert' aria-hidden='true' &times;
            = flash[:error]
      - elsif flash[:alert]
          div class='alert alert-info'
            button type='button' class='close' data-dismiss='alert' aria-hidden='true' &times;
            = flash[:alert]

      div class='content'
          = yield
      
/    footer class='footer'
/      p Mohki Productions ™

app/views/layouts/header.html.slim
div class='header'
  div class='container'
    div class='navbar-header'
      div
        = link_to 'Writz', root_path, class: 'navbar-brand'
    div class='collapse navbar-collapse'
      ul class='nav navbar-nav'
        li
          = link_to 'Home', root_path
        li
          = link_to 'About', welcome_about_path
        li
          = link_to 'Stories', stories_path
        li
          div class='input-group input-group-sm' id='search'
            span class='input-group-addon glyphicon glyphicon-search'
            input type='text' class='form-control' placeholder='Search'
      ul class='nav navbar-nav navbar-right'
        - if current_user
          li 
            = link_to "#{current_user.name}'s account", edit_user_registration_path, class: 'header-greeting'
          li
            = link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          li
            = link_to 'Sign in', new_user_session_path
          li
            = link_to 'Sign up', new_user_registration_path

app/views/stories/_form.html.slim
= form_for(@story) do |f|

  - if @story.errors.messages[:title]
    div class='has-error'
      = f.text_field :title, class: 'form-control input-lg', autofocus: true
      = 'Title ' + @story.errors.messages[:title].first + '!'
  - else
    div 
      = f.text_field :title, class: 'form-control input-lg', autofocus: true
  br
  div
    = f.submit 'Create', class: 'btn btn-lg btn-primary btn-block'

app/views/stories/index.html.slim
div class='row stories-container'
  - if current_user
    = button_to 'New story', new_story_path, method: :get, class: 'btn btn-primary btn-lg'
  - else
    = button_to 'New story', new_user_registration_path, method: :get, class: 'btn btn-primary btn-lg'
  br
  div class='col-md-4 list-group'
    - @stories.each do |s|
      = link_to story_path(s), class: 'list-group-item story-link', data: {id: s.id} do
        h4 class='list-group-item-heading'
          = s.title
        p class='list-group-item-text'
          - if s.intro
            = truncate s.intro.body, length: 40
          - else
            = 'This story needs an introduction!'
    = will_paginate @stories, renderer: BootstrapPagination::Rails, bootstrap: 3
  div class='col-md-8 selected-story'

app/views/stories/new.html.slim
div class='new-story'
  h3 Your story needs a title...
  br
  = render partial: 'form'

app/views/stories/show.html.slim
h2
  = link_to @story.title, @story

div class='story-component' data-scid='#{@intro_id}' data-sid='#{@story.id}'
  p
    = markdown(@intro_body).html_safe

div class='story-component' data-scid='#{@conflict_id}' data-sid='#{@story.id}'
  p
    = markdown(@conflict_body).html_safe

div class='story-component' data-scid='#{@resolution_id}' data-sid='#{@story.id}'
  p
    = markdown(@resolution_body).html_safe


ul class='dropdown-menu' tabindex='-1'
  li id='edit'
    a href='' Edit
  li id='add'
    a href='' Add component

app/views/story_components/_form.html.slim
= form_for [@story, @story_component] do |f|

  = f.hidden_field :contributer_id

  br
  div
    = f.label :component_type, 'Section of story:&nbsp;'.html_safe
    = f.select :component_type, @component_types, autofocus: true
  
  br
  - if @story_component.errors.messages[:body]
    div class="has-error"
      = f.text_area :body, 
        class: 'form-control input-lg', 
        value: @story_component.body,
        data: {provide: 'markdown'},
        rows: 15,
        autofocus: true
      = 'Component ' + @story_component.errors.messages[:body].first + '!'
  - else
    div
      = f.text_area :body, 
        class: 'form-control input-lg', 
        value: @story_component.body, 
        placeholder: 'Write your part of the story here!',
        data: {provide: 'markdown'},
        rows: 15,
        autofocus: true
  
  br
  div
    = f.submit 'Save', class: 'btn btn-lg btn-primary btn-block'

app/views/story_components/edit.html.slim
div class='sc-forms'
  = render 'form'

app/views/story_components/new.html.slim
div class='sc-forms'
  = render 'form'

app/views/welcome/about.html.slim
div class='about'
  h1 Writz
  br
  p class='lead' a collaborative storytelling tool that lets you create, submit, vote on, and combine story elements into one shared narrative.

app/views/welcome/index.html.slim
div class='welcome'
  h1 Write a Story Together!
  br
  p 
    = link_to 'Get started', stories_path, class: 'btn btn-primary btn-lg'
div class='row top-stories'
  - @top_stories.each do |s|
    div class='col-6 col-sm-6 col-lg-4'
      h2 
        = truncate s.title, length: 20
      p 
        - if s.intro
          = truncate markdown(s.intro.body).html_safe, length: 425
        - else
          = 'This story needs an introduction!'
      p
        = link_to 'Read', story_path(s), class: 'btn btn-default'